#!/usr/bin/env bash
# This script pings an IP address passed as an argument. If no argument is provided, it displays usage information.

if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

ping -c 5 "$1"
